# Generated by Django 4.2.3 on 2023-08-30 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_banner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
